package recall

import (
	"context"
	"encoding/json"
	"errors"
	"math"
	"os"
	"reflect"
	"slices"
	"testing"
	"time"
)

// Fixtures were computed independently using Python hashlib and IEEE-754
// struct.pack, not regenerated by the implementation under test.
func TestAuditGoldenCompatibility(t *testing.T) {
	raw, err := os.ReadFile("testdata/audit-v1.json")
	if err != nil {
		t.Fatal(err)
	}
	var b AuditBundle
	if err := json.Unmarshal(raw, &b); err != nil {
		t.Fatal(err)
	}
	got, err := b.Replay()
	if err != nil || len(got) != 1 || got[0].Value != "Neovim" {
		t.Fatalf("golden replay = %+v, %v", got, err)
	}
	if b.Digest != auditFixture(t).Digest {
		t.Fatal("bundle canonical encoding changed")
	}
	raw, err = os.ReadFile("testdata/audit-digests.json")
	if err != nil {
		t.Fatal(err)
	}
	var digests map[string]string
	if err := json.Unmarshal(raw, &digests); err != nil {
		t.Fatal(err)
	}
	for name, digest := range digests {
		if err := VerifyDigest(b.Events, digest); err != nil {
			t.Fatalf("%s golden digest: %v", name, err)
		}
	}
}

func TestDigestV2CoversEveryEventField(t *testing.T) {
	base := assert("a", "Neovim", at(0))
	want, err := DigestV2([]Event{base})
	if err != nil {
		t.Fatal(err)
	}
	for name, mutate := range map[string]func(*Event){
		"id":          func(e *Event) { e.ID = "b" },
		"kind":        func(e *Event) { e.Kind = "fact" },
		"subject":     func(e *Event) { e.Subject = "alice" },
		"predicate":   func(e *Event) { e.Predicate = "likes" },
		"value":       func(e *Event) { e.Value = "neovim" },
		"confidence":  func(e *Event) { e.Confidence = 0.5 },
		"source":      func(e *Event) { e.Source = "tool_result" },
		"retraction":  func(e *Event) { e.Retraction = true },
		"observed_at": func(e *Event) { e.ObservedAt = e.ObservedAt.Add(time.Nanosecond) },
	} {
		t.Run(name, func(t *testing.T) {
			e := base
			mutate(&e)
			if err := VerifyDigest([]Event{e}, want); !errors.Is(err, ErrDigestMismatch) {
				t.Fatalf("field mutation: %v", err)
			}
		})
	}
}

func auditFixture(t *testing.T) AuditBundle {
	t.Helper()
	b := AuditBundle{Version: AuditVersion, EventVersion: EventVersion, FoldVersion: FoldVersion,
		AsOf: at(3 * time.Hour), Registry: Registry{"prefers_editor": {Cardinality: "single", ValueType: "string", Description: "editor"}},
		Events: []Event{assert("a", "Vim", at(0)), assert("b", "Neovim", at(time.Hour)), retract("c", "Vim", at(2*time.Hour))},
	}
	var err error
	b.Digest, err = b.checksum()
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestAuditJSONRoundTripReplaysWithoutStore(t *testing.T) {
	s, _ := seedAuditLog(t)
	for _, scope := range []AuditScope{{}, {Subject: " User "}, {Predicate: " likes "}, {Subject: "user", Predicate: "prefers_editor"}} {
		b, err := s.ExportAudit(AuditRequest{Scope: scope, AsOf: at(2 * time.Hour)})
		if err != nil {
			t.Fatal(err)
		}
		raw, err := json.Marshal(b)
		if err != nil {
			t.Fatal(err)
		}
		var decoded AuditBundle
		if err := json.Unmarshal(raw, &decoded); err != nil {
			t.Fatal(err)
		}
		got, err := decoded.Replay()
		if err != nil {
			t.Fatal(err)
		}
		want, err := s.Recall(Query{Subject: b.Scope.Subject, Predicate: b.Scope.Predicate, AsOf: b.AsOf})
		if err != nil {
			t.Fatal(err)
		}
		// Online broad recall may rank pairs differently; compare the beliefs.
		byID := func(a, b Belief) int {
			if a.EventID < b.EventID {
				return -1
			}
			if a.EventID > b.EventID {
				return 1
			}
			return 0
		}
		slices.SortFunc(got, byID)
		slices.SortFunc(want, byID)
		if len(got) != len(want) || !reflect.DeepEqual(got, want) && len(got) != 0 {
			t.Fatalf("replay = %+v, online = %+v", got, want)
		}
	}
	// Zero AsOf is captured before the read; replay never consults the clock.
	b, err := s.ExportAudit(AuditRequest{})
	if err != nil || !b.AsOf.Equal(at(4*time.Hour)) {
		t.Fatalf("default as_of = %v, %v", b.AsOf, err)
	}
	delete(b.Registry, "likes")
	if _, ok := s.Registry()["likes"]; !ok {
		t.Fatal("bundle mutated store registry")
	}
}

func TestAuditReplaysUsingBundledRegistryAndTime(t *testing.T) {
	b := auditFixture(t)
	got, err := b.Replay()
	if err != nil || len(got) != 1 || got[0].Value != "Neovim" {
		t.Fatalf("replay = %+v, %v", got, err)
	}
	b.Events = b.Events[:2]
	b.Registry["prefers_editor"] = Predicate{Cardinality: "multi", ValueType: "string", Description: "editor"}
	if err := b.Verify(); !errors.Is(err, ErrDigestMismatch) {
		t.Fatalf("registry mutation = %v", err)
	}
	b.Digest, err = b.checksum()
	if err != nil {
		t.Fatal(err)
	}
	got, err = b.Replay()
	if err != nil || len(got) != 2 {
		t.Fatalf("multi registry replay = %+v, %v", got, err)
	}
	b.AsOf = at(0)
	b.Digest, err = b.checksum()
	if err != nil {
		t.Fatal(err)
	}
	got, err = b.Replay()
	if err != nil || len(got) != 1 || got[0].Value != "Vim" {
		t.Fatalf("historical replay = %+v, %v", got, err)
	}
}

func TestAuditDetectsAllInputChanges(t *testing.T) {
	for name, mutate := range map[string]func(*AuditBundle){
		"string case":        func(b *AuditBundle) { b.Events[1].Value = "neovim" },
		"removed retraction": func(b *AuditBundle) { b.Events = b.Events[:2] },
		"instant":            func(b *AuditBundle) { b.AsOf = b.AsOf.Add(time.Nanosecond) },
		"scope":              func(b *AuditBundle) { b.Scope.Subject = "user" },
		"cardinality": func(b *AuditBundle) {
			p := b.Registry["prefers_editor"]
			p.Cardinality = "multi"
			b.Registry["prefers_editor"] = p
		},
		"description": func(b *AuditBundle) {
			p := b.Registry["prefers_editor"]
			p.Description = "changed"
			b.Registry["prefers_editor"] = p
		},
		"registry default encoding": func(b *AuditBundle) {
			p := b.Registry["prefers_editor"]
			p.ValueType = ""
			b.Registry["prefers_editor"] = p
		},
	} {
		t.Run(name, func(t *testing.T) {
			b := auditFixture(t)
			mutate(&b)
			if got, err := b.Replay(); !errors.Is(err, ErrDigestMismatch) || got != nil {
				t.Fatalf("tampered replay = %v, %v", got, err)
			}
		})
	}
}

func TestAuditRejectsInvalidAndUnknownInputs(t *testing.T) {
	for name, mutate := range map[string]func(*AuditBundle){
		"bundle version":          func(b *AuditBundle) { b.Version = "recall-audit-v2" },
		"event version":           func(b *AuditBundle) { b.EventVersion = "recall-event-v2" },
		"fold version":            func(b *AuditBundle) { b.FoldVersion = "recall-fold-v3" },
		"zero instant":            func(b *AuditBundle) { b.AsOf = time.Time{} },
		"bad instant":             func(b *AuditBundle) { b.AsOf = time.Date(10000, 1, 1, 0, 0, 0, 0, time.UTC) },
		"unnormalized scope":      func(b *AuditBundle) { b.Scope.Subject = " USER " },
		"unknown predicate scope": func(b *AuditBundle) { b.Scope.Predicate = "missing" },
		"outside scope":           func(b *AuditBundle) { b.Scope.Subject = "alice" },
		"missing registry":        func(b *AuditBundle) { b.Registry = nil },
		"invalid registry":        func(b *AuditBundle) { b.Registry["bad"] = Predicate{Cardinality: "invalid"} },
		"invalid description":     func(b *AuditBundle) { b.Registry["bad"] = Predicate{Cardinality: "single", Description: "\xff"} },
		"unregistered event":      func(b *AuditBundle) { b.Events[0].Predicate = "missing" },
		"wrong value type":        func(b *AuditBundle) { b.Events[0].Value = false },
		"duplicate id":            func(b *AuditBundle) { b.Events = append(b.Events, b.Events[0]) },
		"malformed event":         func(b *AuditBundle) { b.Events[0].ObservedAt = time.Time{} },
		"oversized bundle":        func(b *AuditBundle) { b.Events = make([]Event, MaxExport+1) },
	} {
		t.Run(name, func(t *testing.T) {
			b := auditFixture(t)
			mutate(&b)
			if got, err := b.Replay(); !errors.Is(err, ErrInvalidAudit) || got != nil {
				t.Fatalf("invalid replay = %v, %v", got, err)
			}
		})
	}
}

func TestAuditCanonicalOrderAndTypedJSON(t *testing.T) {
	b := auditFixture(t)
	b.Registry["number"] = Predicate{Cardinality: "multi", ValueType: "number"}
	b.Registry["boolean"] = Predicate{Cardinality: "single", ValueType: "boolean"}
	for i, v := range []any{math.Copysign(0, -1), math.SmallestNonzeroFloat64, math.MaxFloat64, false} {
		e := assert(string(rune('d'+i)), v, at(time.Minute))
		e.Predicate = "number"
		if i == 3 {
			e.Predicate = "boolean"
		}
		b.Events = append(b.Events, e)
	}
	var err error
	b.Digest, err = b.checksum()
	if err != nil {
		t.Fatal(err)
	}
	slices.Reverse(b.Events)
	b.AsOf = b.AsOf.In(time.FixedZone("offset", 3600))
	for i := range b.Events {
		b.Events[i].ObservedAt = b.Events[i].ObservedAt.In(time.FixedZone("offset", -3600))
	}
	raw, err := json.Marshal(b)
	if err != nil {
		t.Fatal(err)
	}
	var decoded AuditBundle
	if err := json.Unmarshal(raw, &decoded); err != nil {
		t.Fatal(err)
	}
	if err := decoded.Verify(); err != nil {
		t.Fatalf("round trip changed digest: %v", err)
	}
	if got, err := decoded.Replay(); err != nil || len(got) != 5 {
		t.Fatalf("typed replay = %+v, %v", got, err)
	}
}

func TestAuditClientCompletenessAndCancellation(t *testing.T) {
	ctx := t.Context()
	b := newLockedBackend()
	c := clientFor(t, b, nil)
	empty, err := c.ExportAudit(ctx, AuditRequest{})
	if err != nil {
		t.Fatal(err)
	}
	if got, err := empty.Replay(); err != nil || len(got) != 0 {
		t.Fatalf("empty replay = %+v, %v", got, err)
	}
	for name, list := range map[string]func(context.Context, string, map[string]any, int) ([]StoredVector, int, error){
		"partial": func(context.Context, string, map[string]any, int) ([]StoredVector, int, error) { return nil, 2, nil },
		"overflow": func(context.Context, string, map[string]any, int) ([]StoredVector, int, error) {
			return nil, MaxExport + 1, nil
		},
		"backend": func(context.Context, string, map[string]any, int) ([]StoredVector, int, error) {
			return nil, 0, errors.New("offline")
		},
	} {
		t.Run(name, func(t *testing.T) {
			c := clientFor(t, backendFuncs{list: list}, nil)
			if b, err := c.ExportAudit(ctx, AuditRequest{}); !errors.Is(err, ErrIncompleteHistory) || b.Digest != "" {
				t.Fatalf("incomplete bundle escaped: %+v, %v", b, err)
			}
		})
	}
	cancelled, cancel := context.WithCancel(ctx)
	cancel()
	if _, err := c.ExportAudit(cancelled, AuditRequest{}); !errors.Is(err, context.Canceled) {
		t.Fatal(err)
	}
	if _, err := c.ExportAudit(nil, AuditRequest{}); err == nil {
		t.Fatal("nil context accepted")
	}
	during, stop := context.WithCancel(ctx)
	defer stop()
	c = clientFor(t, backendFuncs{list: func(context.Context, string, map[string]any, int) ([]StoredVector, int, error) {
		stop()
		return nil, 0, nil
	}}, nil)
	if b, err := c.ExportAudit(during, AuditRequest{}); !errors.Is(err, context.Canceled) || b.Digest != "" {
		t.Fatalf("cancelled export = %+v, %v", b, err)
	}
}

func TestDigestV2PreservesExactValuesAndLegacyVerification(t *testing.T) {
	events := []Event{assert("a", "Neovim", at(0))}
	legacy := Digest(events)
	v2, err := DigestV2(events)
	if err != nil {
		t.Fatal(err)
	}
	if err := VerifyDigest(events, legacy); err != nil {
		t.Fatal(err)
	}
	if err := VerifyDigest(events, v2); err != nil {
		t.Fatal(err)
	}
	events[0].Value = "neovim"
	if err := VerifyDigest(events, legacy); err != nil {
		t.Fatalf("legacy behavior changed: %v", err)
	}
	if err := VerifyDigest(events, v2); !errors.Is(err, ErrDigestMismatch) {
		t.Fatalf("case change undetected: %v", err)
	}
	if err := VerifyDigest(events, "sha512:unknown"); err == nil {
		t.Fatal("unknown digest accepted")
	}
	digests := map[string]bool{}
	for _, v := range []any{"false", false, float64(0), math.Copysign(0, -1), nil} {
		e := retract("r", v, at(0))
		d, err := DigestV2([]Event{e})
		if err != nil {
			t.Fatal(err)
		}
		if digests[d] {
			t.Fatalf("value lost type/bits: %#v", v)
		}
		digests[d] = true
	}
	for _, v := range []any{math.NaN(), math.Inf(1), "\xff", int(1), []string{"x"}} {
		if _, err := DigestV2([]Event{assert("a", v, at(0))}); !errors.Is(err, ErrInvalidEvent) {
			t.Fatalf("invalid value %v: %v", v, err)
		}
	}
	if _, err := DigestV2([]Event{assert("\xff", "x", at(0))}); !errors.Is(err, ErrInvalidEvent) {
		t.Fatal(err)
	}
	a, _ := DigestV2(nil)
	b, _ := DigestV2([]Event{})
	if a != b {
		t.Fatal("nil/empty digests differ")
	}
}
